
services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password  # Set the root password here
      MYSQL_DATABASE: psikis_app              # Optional, to create a default database
    ports:
      - "3307:3306"  # Expose MySQL port to the host
    volumes:
      - db_data:/var/lib/mysql   # Use a named volume to persist MySQL data

  laravel:
    image: app-sikis-laravel  # Reference your Laravel image or build instructions
    ports:
      - "8000:8000"  # Expose the Laravel app to the host
    depends_on:
      - database
    environment:
      DB_CONNECTION: mysql
      DB_HOST: database  # This should match the MySQL service name
      DB_PORT: 3306
      DB_DATABASE: psikis_app
      DB_USERNAME: root
      DB_PASSWORD: your_root_password  # Must match the MySQL password

  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  db_data:  # Define the volume to persist MySQL data